#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'mysql'

cookbook 'chef-magento',
   :git => 'https://github.com/inviqa/chef-magento'

cookbook 'chef-php-extra',
   :git => 'https://github.com/inviqa/chef-php-extra'


cookbook 'elasticsearch',
    :git => 'https://github.com/elasticsearch/cookbook-elasticsearch'
